name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Basic Antlr
      run: |
        mkdir x
        cd x
        dotnet new -i ../Templates/templates/AntlrCAProject
        dotnet new antlr
        ls ../Antlr4BuildTasks/bin/Debug
        dotnet nuget add source /home/runner/work/Antlr4BuildTasks/Antlr4BuildTasks/bin/Debug
        dotnet restore
        dotnet build
        dotnet run
    - name: Test
      run: dotnet test --no-build --verbosity normal
